#!/bin/bash
#create database

createdatabase() {
	file="./database.txt"

	if [ ! -f "${file}" ]; then
		printf "File database.txt doesn't exit\n"
		printf "Name:Address:Phone:Email\n" >> database.txt
	fi
}
