#!/bin/bash

OFIS=$IFS
IFS=':'

if [ $# -ne 0 ]; then
    pat="$*"
    grep -v -w "$pat" database.txt > datatemp.txt
    mv datatemp.txt database.txt
    IFS=$OIFS
    exit
fi

./specrecord

pattern=$(cat pat.txt)

grep  -v -w "$pattern" database.txt > datatemp.txt
mv datatemp.txt database.txt
echo "$pattern removed."
IFS=$OIFS    


