#!/bin/bash
clear
printf "Records in Database: \n\n"
printf "Name  |  Address  |  Email  |  Phone\n"
echo "------------------------------------"
count=1

while read line; do
	printf "($count) "
	echo $line | tr ":" "|"

	let count=$count+1
done < database.txt
printf "\n\n"
exit 0
