#!/bin/bash
#find record based on user input
source ./helpers
clear
display_records

function name_find() {
	read -e -p "Enter the name of contact to find: " name
	matchname=$(grep -w "^${name}" database.txt)
	if [ -n "${matchname}" ]; then
		clear
		echo "Record match with name "${name}" found: "
		grep -w "^${name}" database.txt
	
	else
		echo "No record with name "${name}" found."
	fi
}

function address_find() {
	read -e -p "Enter the address of contact to find: " address
	matchaddress=$(grep "^\([^:]*:\)\{1\}${address}:" database.txt)
	if [ -n "${matchaddress}" ]; then
		clear
		echo "Record match with address "${address}" found: "
		grep "^\([^:]*:\)\{1\}${address}:" database.txt

	else
		echo "No record with address "${address}" found."
	fi
}

function phone_find() {
	read -e -p "Enter the phone number of contact to find: " phone
	matchphone=$(grep "^\([^:]*:\)\{2\}${phone}:" database.txt)
	if [ -n "${matchphone}" ]; then
		clear
		echo "Record match with phone number "${phone}" found: "
		grep "^\([^:]*:\)\{2\}${phone}:" database.txt
	
	else
		echo "No record with phone number "${phone}" found."
	fi
}

function email_find() {
	read -e -p "Enter the email of contact to find: " email
	matchemail=$(grep "^\([^:]*:\)\{3\}${email}" database.txt)
	if [ -n "${matchemail}" ]; then
		clear
		echo "Record match with email "${email}" found:"
		grep "^\([^:]*:\)\{3\}${email}" database.txt
	
	else
		echo "No record with email "${email}" found."
	fi
}


prompt="Search for a record by:
	(a) name
	(b) address
	(c) phone
	(d) email  
	(x) exit
	>:"

while true; do

    read -p "${prompt}" input    
    case $input in

        a|A) name_find;;
        b|B) address_find;;
        c|C) phone_find;;
        d|D) email_find;;
        x|X) exit 0;;
	*) echo "Incorrect input."; sleep 1s; clear;
    esac
done
