#!/bin/bash

#find record based on user input

prompt="Search for a record by:
	(a) name
	(b) address
	(c) phone
	(d) email  "


    read -p "${prompt}" input
    
    case $input in
        a|A) searchParam="name";;
        b|B) searchParam="address";;
        c|C) searchParam="phone number";;
        d|D) searchParam="email";;
        *) exit 0;;
    esac
verification="You want to search records by $searchParam?"

read -p "${verifyPrompt}" verification

#exit 0
