#!/bin/bash


prompt="Please select from the following options:
	(a) Find a record
	(b) Add a new record
	(c) Update a record
	(d) Remove a record
	(h) Help
	(e) Quit
	>:" 
while true; do

	read -p "${prompt}" input
	case "${input}" in
		"a"|"A") 	./addrecord;;
		*) 		exit 0;;

		"b"|"B")	./findrecord;;
		*)		exit 0;;
	esac
done
