#!/bin/bash
#prompts for adding a new record
namePrompt="Enter Name: "
addressPrompt="Enter Address: "  
emailPrompt="Enter E-mail: "
phonePrompt="Enter Phone: "

#prompts for updating record
udpateRecordPrompt="Which record would you like to replace? : "
newRecordPrompt="What is the new record? :"
		 


while getopts "naepur" opt; do
	case $opt in
	  n)  echo "$namePrompt";;
	  a)  echo "$addressPrompt";;
	  e)  echo "$emailPrompt";;
	  p)  echo "$phonePrompt";;
	  u)  echo "$updaateRecordPrompt";;
	  r)  echo "$newRecordPrompt";;
	esac
done
