#!/bin/bash
#specrecord
next=1

while true; do 
    case "$next" in
        1) echo "Enter Name: " 
            ;;
        2) echo "Enter Address: " 
            ;;
        3) echo "Enter Phone Number: " 
            ;;
        4) echo "Enter Email: " 
            ;;
        *) echo "Record Not Found"
           exit 0
           break;;
    esac

    if [ $next -eq 1 ]; then
        read appen
        pattern=$appen
    else
        read appen
        pattern=$pattern:$appen
    fi
    val=$(grep -c -w "$pattern" database.txt)
    if [ ${val} -ne 1 ]; then
        next=$((next+1))
    else
        grep -w "$pattern" database.txt > pat.txt
        break;
    fi
done

echo -n "Target Record: "
cat pat.txt



 
