#!/bin/bash
#update record

prompt=":
	Which record whould you like to replace
	>: "

promptnew=":
	   What is the new record?
	   >: "

	
	while read line; do
	echo "$line"
	done < database.txt

	read -p "${prompt}" input        
	
	read -p "${promptnew}" newinput
	
	sed  -i -e "s/${input}/${newinput}/g" database.txt

exit 0
