#!/bin/bash
#update record

source ./helpers

display_records

# reads in each line of database.txt to an index in the array, 'lines'
IFS=$'\n' read -d '' -r -a lines < database.txt

prompt="Which record line whould you like to replace?
	>: "
updateConfirm="You want to update this record?"
promptnew="What is the new record?
	   >: "

#input is the user's line selection
read -p "${prompt}" input        

read -p "${updateConfirm}: ${lines[$input]}: " confirmation
#printf "${lines[$input]}\n"

case $confirmation in
	y|Y) echo "FILE UPDATED" ;;
	n|N) echo "FILE NOT UPDATED" ;;
	*) echo "don't know" ;;
esac
 #input_record     #calls input_record function from ./helpers


#if [ ${#} -ne 4 ]; then
#       	echo "Illegal number of parameters"
# 	exit 0
#fi




exit 0
